In [3]:
DATA_DIR = "../data"

In [4]:
import pandas as pd

df = pd.read_csv(f"{DATA_DIR}/raw/results.csv")

display(df.head())
display(df.describe())

,Unnamed: 0,date,team_1,team_2,_map,result_1,result_2,map_winner,starting_ct,ct_1,t_2,t_1,ct_2,event_id,match_id,rank_1,rank_2,map_wins_1,map_wins_2,match_winner
0,0,2020-03-18,Recon 5,TeamOne,Dust2,0,16,2,2,0,1,0,15,5151,2340454,62,63,0,2,2
1,1,2020-03-18,Recon 5,TeamOne,Inferno,13,16,2,2,8,6,5,10,5151,2340454,62,63,0,2,2
2,2,2020-03-18,New England Whalers,Station7,Inferno,12,16,2,1,9,6,3,10,5243,2340461,140,118,12,16,2
3,3,2020-03-18,Rugratz,Bad News Bears,Inferno,7,16,2,2,0,8,7,8,5151,2340453,61,38,0,2,2
4,4,2020-03-18,Rugratz,Bad News Bears,Vertigo,8,16,2,2,4,5,4,11,5151,2340453,61,38,0,2,2

,Unnamed: 0,result_1,result_2,map_winner,starting_ct,ct_1,t_2,t_1,ct_2,event_id,match_id,rank_1,rank_2,map_wins_1,map_wins_2,match_winner
count,45773.000000,45773.000000,45773.000000,45773.000000,45773.000000,45773.000000,45773.000000,45773.000000,45773.000000,45773.000000,4.577300e+04,45773.000000,45773.000000,45773.000000,45773.000000,45773.000000
mean,22886.000000,13.385489,12.731545,1.462478,1.501387,6.659515,6.057283,6.375571,6.335482,3580.790859,2.321278e+06,68.394228,77.289428,4.896708,4.597710,1.464204
std,13213.671273,4.417713,4.715722,0.498596,0.500004,3.257815,3.161310,3.184036,3.285287,904.337168,1.170610e+04,61.835919,65.708309,6.044017,5.931323,0.498722
min,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,820.000000,2.299001e+06,1.000000,1.000000,0.000000,0.000000,1.000000
25%,11443.000000,11.000000,9.000000,1.000000,1.000000,4.000000,4.000000,4.000000,4.000000,2818.000000,2.311132e+06,22.000000,28.000000,1.000000,1.000000,1.000000
50%,22886.000000,16.000000,16.000000,1.000000,2.000000,7.000000,6.000000,6.000000,6.000000,3572.000000,2.321956e+06,49.000000,58.000000,2.000000,2.000000,1.000000
75%,34329.000000,16.000000,16.000000,2.000000,2.000000,9.000000,8.000000,9.000000,9.000000,4346.000000,2.331691e+06,96.000000,110.000000,8.000000,7.000000,2.000000
max,45772.000000,38.000000,41.000000,2.000000,2.000000,15.000000,16.000000,15.000000,15.000000,5248.000000,2.340461e+06,404.000000,404.000000,34.000000,34.000000,2.000000